// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/09/2025, 09.22.55
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/kindi/absen-api/front-end/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kindi/absen-api/front-end/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kindi/absen-api/front-end/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kindi/absen-api/front-end/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kindi/absen-api/front-end/plugins/**/*.{js,ts,mjs}","C:/Users/kindi/absen-api/front-end/composables/**/*.{js,ts,mjs}","C:/Users/kindi/absen-api/front-end/utils/**/*.{js,ts,mjs}","C:/Users/kindi/absen-api/front-end/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kindi/absen-api/front-end/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kindi/absen-api/front-end/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kindi/absen-api/front-end/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;